name: Build Installers

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    name: Build ${{ matrix.display }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            display: Linux
          - os: windows-latest
            display: Windows
          - os: macos-latest
            display: macOS
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      CSC_IDENTITY_AUTO_DISCOVERY: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install Linux packaging dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y rpm xz-utils libarchive-tools

      - name: Install dependencies
        run: npm ci

      - name: Build distributables
        run: npm run dist -- --publish always

      - name: Upload packaged artifacts
        uses: actions/upload-artifact@v4
        with:
          name: geco-${{ matrix.display }}
          path: dist/
          if-no-files-found: warn
